import { ColumnDef } from '@app-types';

export const columns: ColumnDef[] = [
  { key: 'priority', label: 'Priority' },
  { key: 'r1', label: 'R1' },
  { key: 'r2', label: 'R2' },
  { key: 'equipment', label: 'Equipment' },
  { key: 'vpo', label: 'VPO' },
  { key: 'vpoForecastQuantity', label: 'Forecast Qty', class: 'text-right' },
  { key: 'testTimePerUnit', label: 'Test Time', class: 'text-right' },
  { key: 'locationCode', label: 'Location' },
  { key: 'vpoSource', label: 'VPO Source' },
  { key: 'vpoDescription', label: 'VPO Description' },
  { key: 'stepSequence', label: 'Step Sequence' },
  { key: 'step', label: 'Step' },
  { key: 'engineerName', label: 'Engineer Name' },
  { key: 'stepComment', label: 'Step Comment' },
  { key: 'product', label: 'Product' },
  { key: 'partType', label: 'Part Type' },
  { key: 'stepState', label: 'Step State' },
  { key: 'engId', label: 'Eng ID' },
  { key: 'vpoType', label: 'VPO Type' },
  { key: 'stepType', label: 'Step Type' },
  { key: 'activityType', label: 'Activity Type' },
  { key: 'stepSpecialInstruction', label: 'Special Instruction' },
  { key: 'stepTimeDuration', label: 'Step Duration' },
  { key: 'recipe', label: 'Recipe' },
  { key: 'lastChangesBy', label: 'Last Changes By' },
  { key: 'hri', label: 'HRI' },
  { key: 'mrv', label: 'MRV' },
  { key: 'qdf', label: 'QDF' },
];
